version: '1.0.{build}'
image: Visual Studio 2019
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./Evolve.Migrations.Helper/Evolve.Migrations.Helper.csproj
build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet publish -c Release ./Evolve.Migrations.Helper/Evolve.Migrations.Helper.csproj
after_build:
  # For once the build has completed
artifacts:
 - path: './Evolve.Migrations.Helper/bin/Release/netcoreapp3.1/publish'
   name: evolve-migrations-helper
   type: WebDeployPackage
clone_depth: 1
test_script:
  # restore packages for our unit tests
  # - cmd: dotnet restore ./tests/tests.csproj --verbosity m
  # run the unit tests (requires changing into the test directory)
  # - cmd: cd tests
  # - cmd: dotnet xunit
on_finish :
  # any cleanup in here
deploy:
  tag: 'Evolve Migrations Helper v$(appveyor_build_version)'
  release: 'Evolve Migrations Helper v$(appveyor_build_version)'  
  provider: GitHub
  auth_token:
    secure: 2b221883d67177fbd50d4f579a1da3e4b710bad5
  artifact: evolve-migrations-helper
  draft: false
  prerelease: true
  on:
    branch: master
    APPVEYOR_REPO_TAG: true