deploy:
  tag: 'Evolve Migrations Helper v$(appveyor_build_version)'
  release: 'Evolve Migrations Helper v$(appveyor_build_version)'  
  provider: GitHub
  auth_token:
    secure: 2b221883d67177fbd50d4f579a1da3e4b710bad5
  artifact: evolve-migrations-helper
  draft: false
  prerelease: true
  on:
    branch: master
    APPVEYOR_REPO_TAG: true