version: '1.0.{build}'
image: 
  - Ubuntu
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - sh: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
dotnet_csproj:
  patch: true
  file: '**\Evolve.Migrations.Helper.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
  - sh: 'echo Packaging version: $APPVEYOR_BUILD_VERSION'
  # Display .NET Core version  
  - sh: dotnet --list-sdks
  # Display minimal restore text
  - sh: dotnet restore ./Evolve.Migrations.Helper/Evolve.Migrations.Helper.csproj
build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - sh: dotnet publish -c Release ./Evolve.Migrations.Helper/Evolve.Migrations.Helper.csproj -f netcoreapp3.1 -r win-x64 --no-self-contained
  - sh: dotnet publish -c Release ./Evolve.Migrations.Helper/Evolve.Migrations.Helper.csproj -f netcoreapp3.1 -r linux-x64 --no-self-contained
after_build:
  # For once the build has completed
artifacts:
 - path: './Evolve.Migrations.Helper/bin/Release/netcoreapp3.1/win-x64/publish' 
   name: evolve-migrations-helper_$(APPVEYOR_BUILD_VERSION)_win-x64
   type: WebDeployPackage

 - path: './Evolve.Migrations.Helper/bin/Release/netcoreapp3.1/linux-x64/publish'
   name: 'evolve-migrations-helper_$(APPVEYOR_BUILD_VERSION)_linux-x64'
   type: WebDeployPackage
clone_depth: 1
test_script:
  # restore packages for our unit tests
  # - cmd: dotnet restore ./tests/tests.csproj --verbosity m
  # run the unit tests (requires changing into the test directory)
  # - cmd: cd tests
  # - cmd: dotnet xunit
on_finish :
  # any cleanup in here
deploy: off